name: iOS Build

on:
  push:
  workflow_dispatch:

jobs:
  build-ios:
    name: Build for iOS
    runs-on: macos-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.1.7

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Install Haxelibs
        run: |
          chmod +x ./setup/install-haxelibs-unix.sh
          sh ./setup/install-haxelibs-unix.sh

      - name: Build for iOS
        run: haxelib run lime build ios -release

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: Flixel HScript - iOS Build
          path: export/release/ios